spring.application.name=placement-portal
spring.datasource.url=jdbc:mysql://gateway01.ap-southeast-1.prod.alicloud.tidbcloud.com:4000/placement_portal?sslMode=VERIFY_IDENTITY

spring.datasource.username=XVYERcYyDejaSnd.root
spring.datasource.password=dHj7yRAP0zL4xeu0

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT
jwt.secret=change-this-secret-to-a-long-random-string-of-at-least-64-chars-keep-it-safe
jwt.expiry-ms=86400000